# Commands to start on workspace startup
tasks:
  - name: Install Lean
    before: printf 'export PATH="$HOME/.elan/bin:$PATH"\n' >> $HOME/.bashrc && exit
    init: curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain leanprover/lean4:nightly -y
